import type { CmsHierarchy, CmsAppItem } from './types';

export function generateCmsHierarchy(): CmsHierarchy {
  const apps: CmsAppItem[] = [
    // 0. AMY AGENTIC OS (7D ARMS COCKPIT)
    {
      id: 'agentic-os',
      name: 'Agentic OS (Interface Amy)',
      domaine: 'l1-life',
      kind: 'singleton',
      icon: '⬡',
      description: 'Cockpit Haptique Déterministe d\'Amy (11e Docteur) • Pyramide à 7 Niveaux (1D-7D) & A.R.M.S Matrix.',
      level: 1,
      views: [
        {
          id: '7d-war-room',
          name: '7D · War Room & Hivemind',
          headerOrSidebar: 'header',
          icon: '🏛️',
          badge: 'Hivemind 7D',
          description: 'Arbitrage multi-agents, commande /standup 24h et bascule flux audio TTS Daemon.',
          level: 2,
          sections: [
            {
              id: 'sec-hivemind-standup',
              title: 'Standup & Consensus Agents',
              category: 'kpi',
              icon: '🎙️',
              description: 'Consolidation des mémoires A2 (12WY, PARA, GTD, Ikigai).',
              level: 3,
              dataset: [
                {
                  id: 'ds-standup-24h',
                  name: 'Consolidation /standup',
                  type: 'standup_result',
                  status: 'VERIFIED',
                  icon: '⚡',
                  description: 'Rapport d\'exécution unifié généré par la War Room.',
                  level: 4,
                  fields: [
                    { key: 'score_12wy', label: 'Score 12WY', type: 'badge', value: '92%', color: 'emerald' },
                    { key: 'audio_channel', label: 'Canal Audio', type: 'string', value: 'antigravity_tts_daemon.py' },
                  ],
                  actions: [
                    { id: 'act-trigger-standup', label: 'Lancer /standup global', verb: 'POST', endpoint: '/api/tech-os/kernel-state' },
                  ],
                  rawAudit: { dimension: '7D', standup_status: 'ok' },
                },
              ],
            },
          ],
        },
        {
          id: '6d-soul-router',
          name: '6D · Soul & Meta-Routeur',
          headerOrSidebar: 'sidebar',
          icon: '📜',
          badge: 'Ancrage DOX',
          description: 'Aiguillage DOX (AGENTS.md local) et jauges d\'horizons Ikigai (H1 à H90).',
          level: 2,
          sections: [
            {
              id: 'sec-dox-ikigai',
              title: 'Ancrage DOX & Horodateur Ikigai',
              category: 'table',
              icon: '📁',
              description: 'Inspecteur AGENTS.md et alignement d\'horizon.',
              level: 3,
              dataset: [
                {
                  id: 'ds-dox-active',
                  name: 'Contexte Actif DOX',
                  type: 'dox_context',
                  status: 'ANCHORED',
                  icon: '📜',
                  description: 'Répertoire maître ciblé sous A\'Space OS V3.',
                  level: 4,
                  fields: [
                    { key: 'active_path', label: 'Chemin Actif', type: 'badge', value: '10_Tech_OS', color: 'orange' },
                    { key: 'horizon', label: 'Horizon Ikigai', type: 'badge', value: 'H1', color: 'blue' },
                  ],
                  actions: [
                    { id: 'act-inspect-agents-md', label: 'Inspecter AGENTS.md', verb: 'INSPECT' },
                  ],
                  rawAudit: { dimension: '6D', path: '10_Tech_OS/AGENTS.md' },
                },
              ],
            },
          ],
        },
        {
          id: '5d-deterministic-guards',
          name: '5D · Deterministic Guard HUD',
          headerOrSidebar: 'sidebar',
          icon: '🛡️',
          badge: 'Circuit Breakers',
          description: 'Pre-Tool Guard (DLP/Secrets), Rot Rate (> 7 jours) et Post-Build SSSF Gates.',
          level: 2,
          sections: [
            {
              id: 'sec-guard-breakers',
              title: 'Coupe-Circuits & Guards',
              category: 'kpi',
              icon: '🔒',
              description: 'Témoins d\'état des circuits-coupeurs de runtime.',
              level: 3,
              dataset: [
                {
                  id: 'ds-pretool-guard',
                  name: 'Pre-Tool Guard (DLP)',
                  type: 'guard_status',
                  status: 'PASSED',
                  icon: '🛡️',
                  description: 'Validation de l\'absence de fuites de secrets ou tokens API.',
                  level: 4,
                  fields: [
                    { key: 'dlp_status', label: 'Statut DLP', type: 'badge', value: 'CLEAN', color: 'emerald' },
                    { key: 'violations', label: 'Violations', type: 'number', value: 0 },
                  ],
                  actions: [
                    { id: 'act-toggle-dlp', label: 'Basculer Guard', verb: 'POST' },
                  ],
                  rawAudit: { dimension: '5D', dlp_passed: true },
                },
              ],
            },
          ],
        },
        {
          id: '4d-cadence-ticker',
          name: '4D · Cadence Ticker & Routines',
          headerOrSidebar: 'sidebar',
          icon: '🕒',
          badge: 'Cycles Circadiens',
          description: 'Scorecard 12WY, Verrou Strategic Block (Mode Deep Work 3h) et Crons Hermes 24/7.',
          level: 2,
          sections: [
            {
              id: 'sec-cadence-routines',
              title: 'Scorecard & Timer Deep Work',
              category: 'table',
              icon: '🔒',
              description: 'Widget de cadencement opérationnel.',
              level: 3,
              dataset: [
                {
                  id: 'ds-strategic-block',
                  name: 'Strategic Block (Deep Work)',
                  type: 'deep_work_timer',
                  status: 'UNLOCKED',
                  icon: '🔓',
                  description: 'Isolation complète de l\'interface pendant les sessions de travail profond.',
                  level: 4,
                  fields: [
                    { key: 'scorecard_12wy', label: 'Score 12WY', type: 'badge', value: '92%', color: 'emerald' },
                    { key: 'next_cron', label: 'Prochain Cron', type: 'string', value: '23m 40s' },
                  ],
                  actions: [
                    { id: 'act-toggle-strategic-block', label: 'Activer Mode 3h', verb: 'POST' },
                  ],
                  rawAudit: { dimension: '4D', strategic_block: false },
                },
              ],
            },
          ],
        },
        {
          id: '3d-amy-omnibar',
          name: '3D · Amy Omnibar & Skills Deck',
          headerOrSidebar: 'sidebar',
          icon: '⚡',
          badge: 'Cmd+K Palette',
          description: 'Palette de commandes universelle, sélecteur d\'effort (Low/Medium/High/XHigh) et substrat d\'exécution.',
          level: 2,
          sections: [
            {
              id: 'sec-omnibar-deck',
              title: 'Skills Deck & Invocations',
              category: 'table',
              icon: '⌘',
              description: 'Centre de commande inspiré du Skills Deck de Jay E.',
              level: 3,
              dataset: [
                {
                  id: 'ds-active-substrate',
                  name: 'Substrat Modèle Actif',
                  type: 'model_substrate',
                  status: 'ACTIVE',
                  icon: '🤖',
                  description: 'Modèle de raisonnement sous-jacent sélectionné.',
                  level: 4,
                  fields: [
                    { key: 'model', label: 'Modèle', type: 'badge', value: 'Claude 3.7 Sonnet', color: 'purple' },
                    { key: 'effort', label: 'Effort', type: 'badge', value: 'MEDIUM', color: 'orange' },
                  ],
                  actions: [
                    { id: 'act-execute-cmd', label: 'Exécuter Commande /', verb: 'POST' },
                  ],
                  rawAudit: { dimension: '3D', model: 'claude-3-7-sonnet' },
                },
              ],
            },
          ],
        },
        {
          id: '2d-river-event-stream',
          name: '2D · River Event Stream & Micro Apps',
          headerOrSidebar: 'sidebar',
          icon: '🌊',
          badge: 'Webhooks & Artifacts',
          description: 'Flux d\'événements asynchrones, Dead Letter Queue (DLQ), carrousel d\'actifs et micro-apps.',
          level: 2,
          sections: [
            {
              id: 'sec-river-stream',
              title: 'Ticker Webhooks & Carrousel d\'Actifs',
              category: 'table',
              icon: '📁',
              description: 'Zone de télémétrie asynchrone n8n / River.',
              level: 3,
              dataset: [
                {
                  id: 'ds-river-stream-events',
                  name: 'Flux Webhooks Ingestion',
                  type: 'webhook_stream',
                  status: 'STREAMING',
                  icon: '🌊',
                  description: 'Événements absorbés en temps réel par le bus.',
                  level: 4,
                  fields: [
                    { key: 'dlq_status', label: 'DLQ Status', type: 'badge', value: 'PROPRE (0)', color: 'emerald' },
                    { key: 'artifacts_count', label: 'Actifs Indexés', type: 'number', value: 4 },
                  ],
                  actions: [
                    { id: 'act-clear-dlq', label: 'Purger DLQ', verb: 'POST' },
                  ],
                  rawAudit: { dimension: '2D', dlq_count: 0 },
                },
              ],
            },
          ],
        },
        {
          id: '1d-silver-platter-grid',
          name: '1D · Silver Platter Grid (Data Pantry)',
          headerOrSidebar: 'sidebar',
          icon: '📊',
          badge: 'Materialized Views',
          description: 'Grille centrale de KPIs synthétiques alimentée par uc.db, sssf.db et Supabase WAL.',
          level: 2,
          sections: [
            {
              id: 'sec-silver-platter-kpis',
              title: 'Vues Matérialisées (Zero JSON Brut)',
              category: 'kpi',
              icon: '💎',
              description: 'Données pré-mâchées condensées en ratios opérationnels.',
              level: 3,
              dataset: [
                {
                  id: 'ds-wal-health',
                  name: 'Santé Pantry WAL',
                  type: 'wal_health',
                  status: 'OPTIMAL',
                  icon: '🗄️',
                  description: 'Statut des connexions SQLite WAL locales et Supabase.',
                  level: 4,
                  fields: [
                    { key: 'uc_db', label: 'uc.db WAL', type: 'badge', value: 'HEALTHY', color: 'emerald' },
                    { key: 'sssf_db', label: 'sssf.db WAL', type: 'badge', value: 'HEALTHY', color: 'emerald' },
                    { key: 'supabase', label: 'Supabase', type: 'badge', value: 'CONNECTED', color: 'emerald' },
                  ],
                  actions: [
                    { id: 'act-refresh-pantry', label: 'Actualiser Vues', verb: 'GET', endpoint: '/api/tech-os/kernel-state' },
                  ],
                  rawAudit: { dimension: '1D', uc_db: 'healthy' },
                },
              ],
            },
          ],
        },
      ],
    },

    // 1. DOCTOR 13 KERNEL
    {
      id: 'doctor-13-kernel',
      name: '13e Docteur · Kernel Core',
      domaine: 'l0-tech',
      kind: 'singleton',
      icon: '⚙️',
      description: 'Substrat L0 Tech OS & Gouvernance Machine · 13e Docteur, Yas, Ryan, Graham.',
      level: 1,
      views: [
        {
          id: 'docteur',
          name: '13e Docteur · Souveraineté L0',
          headerOrSidebar: 'header',
          icon: '🪐',
          badge: 'Kernel Core',
          description: 'Orchestration centrale du noyau SQLite uc.db, baux de possession et lois fondamentales de réplication.',
          level: 2,
          sections: [
            {
              id: 'sec-kernel-kpis',
              title: 'Jauges Souveraines L0 & Baux',
              category: 'kpi',
              icon: '🛡️',
              description: 'Statut du noyau transactionnel et conformité des verrous ACID.',
              level: 3,
              dataset: [
                {
                  id: 'kpi-kernel-db',
                  name: 'Noyau uc.db',
                  type: 'database',
                  status: 'LOCKED_ACID',
                  icon: '🗄️',
                  description: 'Base de données SQLite centrale sous 10_Tech_OS/kernel/uc.db',
                  level: 4,
                  fields: [
                    { key: 'mode', label: 'Journal Mode', type: 'badge', value: 'WAL', color: 'emerald' },
                    { key: 'foreign_keys', label: 'PRAGMA Foreign Keys', type: 'badge', value: 'ON', color: 'emerald' },
                    { key: 'synchronous', label: 'PRAGMA Synchronous', type: 'badge', value: 'NORMAL', color: 'blue' },
                    { key: 'path', label: 'Chemin Disque', type: 'code', value: 'ASpace_OS_V3/10_Tech_OS/kernel/uc.db' },
                  ],
                  actions: [
                    { id: 'act-check-db', label: 'Vérifier intégrité SQLite', verb: 'INSPECT', endpoint: '/api/tech-os/kernel-state' },
                  ],
                  rawAudit: { db: 'uc.db', integrity: 'ok', foreign_keys: 1, wal: true },
                },
                {
                  id: 'kpi-leases-active',
                  name: 'Baux Actifs & Échéances',
                  type: 'leases',
                  status: 'ENFORCED',
                  icon: '⏳',
                  description: 'Gestion des baux décentralisés avec restitution automatique à la file en cas de timeout',
                  level: 4,
                  fields: [
                    { key: 'ttl_default', label: 'TTL Défaut', type: 'string', value: '300 s' },
                    { key: 'reclaim_policy', label: 'Règle de libération', type: 'badge', value: 'Auto-Reclaim', color: 'emerald' },
                  ],
                  actions: [
                    { id: 'act-reclaim-leases', label: 'Purger baux expirés', verb: 'POST', endpoint: '/api/tech-os/leases/purge' },
                  ],
                  rawAudit: { policy: 'Loi du bail non négociable', auto_expire: true },
                },
              ],
            },
            {
              id: 'sec-kernel-events',
              title: 'Journal d’Audit & Transactions',
              category: 'logs',
              icon: '📜',
              description: 'Historique des événements immuables et transitions d’états.',
              level: 3,
              dataset: [
                {
                  id: 'row-kernel-boot',
                  name: 'Démarrage Noyau V2',
                  type: 'audit_event',
                  status: 'CONFIRMED',
                  icon: '⚡',
                  description: 'Initialisation du démon d’écoute et vérification des verrous.',
                  level: 4,
                  fields: [
                    { key: 'operator', label: 'Opérateur', type: 'string', value: 'amdkn' },
                    { key: 'layer', label: 'Couche', type: 'badge', value: 'L0_TECH', color: 'cyan' },
                    { key: 'timestamp', label: 'Horodatage EDT', type: 'date', value: '2026-09-07T16:20:00-04:00' },
                  ],
                  actions: [
                    { id: 'act-inspect-event', label: 'Inspecter trace', verb: 'INSPECT' },
                  ],
                  rawAudit: { event: 'KERNEL_BOOT', trace_id: 'evt-001', verified: true },
                },
              ],
            },
          ],
        },
        {
          id: 'yas',
          name: 'Yas · Télémétrie & Heartbeat',
          headerOrSidebar: 'header',
          icon: '📡',
          badge: 'Monitoring 60s',
          description: 'Observabilité en temps réel du substrat hôte : CPU, RAM, latence IPC et santé des démons.',
          level: 2,
          sections: [
            {
              id: 'sec-yas-gauges',
              title: 'Jauges Ressources Hôte (Windows)',
              category: 'kpi',
              icon: '📊',
              description: 'Métriques systèmes périodiques rafraîchies toutes les 60s.',
              level: 3,
              dataset: [
                {
                  id: 'row-yas-cpu',
                  name: 'Charge CPU',
                  type: 'metric',
                  status: 'HEALTHY',
                  icon: '⚡',
                  description: 'Pourcentage d’utilisation processeur global.',
                  level: 4,
                  fields: [
                    { key: 'current_val', label: 'Utilisation', type: 'badge', value: '18 %', color: 'emerald' },
                    { key: 'threshold_sla', label: 'Seuil Critique', type: 'string', value: '< 80 %' },
                  ],
                  actions: [
                    { id: 'act-sample-cpu', label: 'Échantillonner CPU', verb: 'GET', endpoint: '/api/tech-os/telemetry' },
                  ],
                  rawAudit: { sample_freq_hz: 1, cores: 8, status: 'ok' },
                },
                {
                  id: 'row-yas-ram',
                  name: 'Mémoire RAM',
                  type: 'metric',
                  status: 'HEALTHY',
                  icon: '💾',
                  description: 'Empreinte RAM des processus ASpace OS V3.',
                  level: 4,
                  fields: [
                    { key: 'allocated_mb', label: 'Alloué Desktop', type: 'string', value: '142 Mo' },
                    { key: 'budget_max', label: 'Plafond Mémoire', type: 'badge', value: '< 190 Mo', color: 'emerald' },
                  ],
                  actions: [
                    { id: 'act-compact-ram', label: 'Inspecter mémoire', verb: 'INSPECT' },
                  ],
                  rawAudit: { rss_bytes: 148897792, heap_used_mb: 84 },
                },
              ],
            },
          ],
        },
        {
          id: 'ryan',
          name: 'Ryan · Builder & Déploiement',
          headerOrSidebar: 'header',
          icon: '🏗️',
          badge: '< 30 min SLA',
          description: 'Usine de compilation continue, isolation et livraison à froid sans friction.',
          level: 2,
          sections: [
            {
              id: 'sec-ryan-pipelines',
              title: 'Pipelines CI/CD & Déploiements',
              category: 'table',
              icon: '🚀',
              description: 'Exécution des recettes de déploiement et des builds de packaging.',
              level: 3,
              dataset: [
                {
                  id: 'row-ryan-build-web',
                  name: 'Build Agent OS Desktop',
                  type: 'pipeline',
                  status: 'READY',
                  icon: '📦',
                  description: 'Compilation Vite + TypeScript pour le bureau souverain.',
                  level: 4,
                  fields: [
                    { key: 'target', label: 'Cible', type: 'string', value: 'dist/' },
                    { key: 'sla', label: 'SLA', type: 'badge', value: '< 15 s', color: 'emerald' },
                    { key: 'tsc_status', label: 'Validation TSC', type: 'badge', value: '0 Erreur', color: 'emerald' },
                  ],
                  actions: [
                    { id: 'act-run-typecheck', label: 'Lancer tsc --noEmit', verb: 'EXEC', endpoint: '/api/tech-os/build/check' },
                  ],
                  rawAudit: { command: 'npm run typecheck', exit_code: 0 },
                },
              ],
            },
          ],
        },
        {
          id: 'graham',
          name: 'Graham · Mémoire Sémantique & Checkpoints',
          headerOrSidebar: 'header',
          icon: '🧠',
          badge: '1 681 Nœuds',
          description: 'Graphe ontologique Semantica (1 681 nœuds, 3 456 arêtes) et checkpoints durables WAL.',
          level: 2,
          sections: [
            {
              id: 'sec-graham-graph',
              title: 'Graphe Sémantique RDF',
              category: 'graph',
              icon: '🕸️',
              description: 'Entités ontologiques connectées du corpus souverain.',
              level: 3,
              dataset: [
                {
                  id: 'node-graham-summary',
                  name: 'Corpus Ontologique Complet',
                  type: 'rdf_graph',
                  status: 'COMPILED',
                  icon: '🌐',
                  description: 'Graphe compilé depuis 70_Onthologies et 40_Memory_Wiki_OKF',
                  level: 4,
                  fields: [
                    { key: 'total_nodes', label: 'Nœuds Totaux', type: 'number', value: 1681 },
                    { key: 'total_edges', label: 'Arêtes Totales', type: 'number', value: 3456 },
                    { key: 'status', label: 'Validation RDF', type: 'badge', value: 'TURTLE_CERTIFIÉ', color: 'emerald' },
                  ],
                  actions: [
                    { id: 'act-recompile-graph', label: 'Recompiler Graphe', verb: 'EXEC', endpoint: '/api/tech-os/graham-graph' },
                  ],
                  rawAudit: { compiler: 'python scripts/compiler_ontologie.py', verified_nodes: 1681 },
                },
              ],
            },
            {
              id: 'sec-graham-checkpoints',
              title: 'Instantanés & Checkpoints SQLite WAL',
              category: 'table',
              icon: '💾',
              description: 'Snapshots froids de la base de données uc.db.',
              level: 3,
              dataset: [
                {
                  id: 'chk-wal-latest',
                  name: 'Checkpoint uc.db.checkpoint_latest',
                  type: 'snapshot',
                  status: 'AVAILABLE',
                  icon: '💿',
                  description: 'Dernière sauvegarde cohérente de la file opérationnelle.',
                  level: 4,
                  fields: [
                    { key: 'format', label: 'Format', type: 'badge', value: 'SQLite-WAL', color: 'cyan' },
                    { key: 'reversibility', label: 'Réversibilité', type: 'badge', value: 'Instantanée', color: 'emerald' },
                  ],
                  actions: [
                    { id: 'act-create-chk', label: 'Créer un snapshot WAL', verb: 'POST', endpoint: '/api/tech-os/graham/checkpoint' },
                  ],
                  rawAudit: { target_file: '10_Tech_OS/kernel/uc.db', pragma: 'wal_checkpoint(TRUNCATE)' },
                },
              ],
            },
          ],
        },
      ],
    },

    // 2. ONTHOLOGY (PALANTIR FOUNDRY PATTERN)
    {
      id: 'onthology',
      name: 'Onthology (Palantir)',
      domaine: 'l0-tech',
      kind: 'singleton',
      icon: '🌐',
      description: 'Plateforme Ontologique Palantir Foundry · Monocle Lineage, 5-Layer Framework, Process Mining, Contour, Vertex, Workshop & Quiver.',
      level: 1,
      views: [
        {
          id: 'lineage',
          name: 'Monocle Lineage',
          headerOrSidebar: 'sidebar',
          icon: '🗺️',
          badge: 'Foundry Dataflow',
          description: 'Lignage de bout en bout des données : Raw -> Clean -> NLP/Extraction -> Ontology -> Applications.',
          level: 2,
          sections: [
            {
              id: 'sec-lineage-layers',
              title: 'Étapes du Pipeline Monocle',
              category: 'graph',
              icon: '🔀',
              description: 'Traversée des sas de données selon la Règle d’or 1 (50_Distillation).',
              level: 3,
              dataset: [
                {
                  id: 'stage-raw',
                  name: 'Couche Raw (Données Brutes & Ingestion)',
                  type: 'lineage_stage',
                  status: 'GATED_50_DISTILLATION',
                  icon: '📥',
                  description: 'Sas de réception inviolable. Aucune note brute n’entre directement dans V3.',
                  level: 4,
                  fields: [
                    { key: 'gate', label: 'Sas de Contrôle', type: 'badge', value: '50_Distillation/', color: 'amber' },
                    { key: 'policy', label: 'Règle d’Or', type: 'string', value: 'Distillation Sémantique Obligatoire' },
                  ],
                  actions: [
                    { id: 'act-audit-gate', label: 'Vérifier Sas 50_Distillation', verb: 'INSPECT' },
                  ],
                  rawAudit: { gate_rule: 'Loi L0 et Règle d’or 1', enforced: true },
                },
                {
                  id: 'stage-ontology',
                  name: 'Couche Ontology (Vérité Formelle)',
                  type: 'lineage_stage',
                  status: 'CERTIFIED',
                  icon: '💎',
                  description: 'Ontologies formelles certifiées dans 70_Onthologies/ sous format RDF / OWL.',
                  level: 4,
                  fields: [
                    { key: 'format', label: 'Format Canonique', type: 'badge', value: 'Turtle (.ttl)', color: 'emerald' },
                    { key: 'validator', label: 'Vérificateur', type: 'string', value: 'pyshacl & rdflib' },
                  ],
                  actions: [
                    { id: 'act-inspect-ontology', label: 'Inspecter 70_Onthologies', verb: 'INSPECT' },
                  ],
                  rawAudit: { ontology_dir: '70_Onthologies/', formal_truth: true },
                },
              ],
            },
          ],
        },
        {
          id: 'framework',
          name: '5-Layer Framework',
          headerOrSidebar: 'sidebar',
          icon: '🏛️',
          badge: 'Architecture',
          description: 'Les 5 couches Palantir Foundry transposées : Substrat, Data Integration, Ontology, Logic & Application.',
          level: 2,
          sections: [
            {
              id: 'sec-layers-detail',
              title: 'Spécification des 5 Couches Souveraines',
              category: 'table',
              icon: '📐',
              description: 'Cartographie des responsabilités opérationnelles.',
              level: 3,
              dataset: [
                {
                  id: 'layer-l0',
                  name: 'L0 : Substrat & Stockage',
                  type: 'framework_layer',
                  status: 'OPERATIONAL',
                  icon: '🧱',
                  description: 'Système de fichiers, SQLite uc.db, baux transactionnels.',
                  level: 4,
                  fields: [
                    { key: 'owner', label: 'Organe Hôte', type: 'string', value: '10_Tech_OS' },
                    { key: 'role', label: 'Rôle', type: 'badge', value: 'Serviteur Silencieux', color: 'blue' },
                  ],
                  actions: [{ id: 'act-view-l0', label: 'Examiner L0', verb: 'INSPECT' }],
                  rawAudit: { layer: 'L0', isolation: true },
                },
                {
                  id: 'layer-l2',
                  name: 'L2 : Vérité Formelle RDF & OKF',
                  type: 'framework_layer',
                  status: 'SOVEREIGN',
                  icon: '📜',
                  description: 'Organes souverains transversaux : 70_Onthologies, 40_Memory_Wiki_OKF.',
                  level: 4,
                  fields: [
                    { key: 'authority', label: 'Autorité', type: 'badge', value: 'Au-dessus de tout', color: 'purple' },
                    { key: 'law', label: 'Règle d’Or', type: 'string', value: 'Règle 2 : Transversalité Souveraine' },
                  ],
                  actions: [{ id: 'act-view-l2', label: 'Examiner L2', verb: 'INSPECT' }],
                  rawAudit: { layer: 'L2', transversal: true },
                },
              ],
            },
          ],
        },
        {
          id: 'contour',
          name: 'Contour Analytics',
          headerOrSidebar: 'sidebar',
          icon: '📈',
          badge: 'Aggregation',
          description: 'Analyse multidimensionnelle et tableaux croisés dynamiques sur les entités du graphe.',
          level: 2,
          sections: [
            {
              id: 'sec-contour-boards',
              title: 'Planches d’Analyse Statistiques',
              category: 'table',
              icon: '📊',
              description: 'Agrégation des degrés de centralité et de distribution des classes sémantiques.',
              level: 3,
              dataset: [
                {
                  id: 'contour-classes',
                  name: 'Distribution des Classes RDF',
                  type: 'analytics_board',
                  status: 'COMPUTED',
                  icon: '🥧',
                  description: 'Comptage des instances par classe OWL / RDFS.',
                  level: 4,
                  fields: [
                    { key: 'top_class', label: 'Classe Dominante', type: 'string', value: 'Concept' },
                    { key: 'entropy', label: 'Homogénéité', type: 'badge', value: 'Optimale (0.84)', color: 'emerald' },
                  ],
                  actions: [{ id: 'act-recalc-contour', label: 'Recalculer Agrégats', verb: 'EXEC' }],
                  rawAudit: { dataset: 'semantica_classes', total_samples: 1681 },
                },
              ],
            },
          ],
        },
        {
          id: 'vertex',
          name: 'Vertex AIP & LLM Reasoning',
          headerOrSidebar: 'sidebar',
          icon: '✨',
          badge: 'Intelligence Native',
          description: 'Co-pilote de raisonnement ontologique et suggestions d’actions guidées par l’OSDK.',
          level: 2,
          sections: [
            {
              id: 'sec-vertex-prompts',
              title: 'Moteurs de Raisonnement AIP',
              category: 'inspector',
              icon: '🧠',
              description: 'Interaction avec les modèles de frontière pour la découverte de concepts manquants.',
              level: 3,
              dataset: [
                {
                  id: 'vertex-eval-engine',
                  name: 'Evaluateur Sémantique Antigravity',
                  type: 'aip_engine',
                  status: 'ACTIVE',
                  icon: '💡',
                  description: 'Génération de triplets RDF assistée par modèle sous contraintes SHACL.',
                  level: 4,
                  fields: [
                    { key: 'model', label: 'Modèle', type: 'badge', value: 'Gemini / Claude', color: 'purple' },
                    { key: 'shacl_guard', label: 'Garde SHACL', type: 'badge', value: 'STRICT', color: 'emerald' },
                  ],
                  actions: [{ id: 'act-trigger-aip', label: 'Évaluer Ontologie', verb: 'POST' }],
                  rawAudit: { model: 'frontier', guard: 'shacl' },
                },
              ],
            },
          ],
        },
      ],
    },

    // 3. DOCTOR 12 BUS
    {
      id: 'doctor-12-bus',
      name: '12e Docteur · Bus Core',
      domaine: 'l2-business',
      kind: 'singleton',
      icon: '📈',
      description: 'Croissance SOB, Franchises 72h & Monopoles $100M · 12e Docteur, Bill, Clara, Nardole.',
      level: 1,
      views: [
        {
          id: 'docteur',
          name: '12e Docteur · Monopole $100M',
          headerOrSidebar: 'header',
          icon: '👑',
          badge: 'SOB Strategy',
          description: 'Direction stratégique des franchises autonomes, pricing d’autorité et suppression de toute dette commerciale.',
          level: 2,
          sections: [
            {
              id: 'sec-bus-pillars',
              title: 'Piliers Stratégiques SOB',
              category: 'kpi',
              icon: '🏛️',
              description: 'Mesure de vélocité commerciale et marges d’autorité.',
              level: 3,
              dataset: [
                {
                  id: 'sob-metric-margin',
                  name: 'Marge Opérationnelle Brute',
                  type: 'financial_kpi',
                  status: 'TARGET_EXCEEDED',
                  icon: '💎',
                  description: 'Modèle économique d’infrastructure sans coûts marginaux récurrents.',
                  level: 4,
                  fields: [
                    { key: 'target', label: 'Cible', type: 'badge', value: '> 90 %', color: 'emerald' },
                    { key: 'current', label: 'Actuel', type: 'string', value: '94.2 %' },
                  ],
                  actions: [{ id: 'act-audit-margin', label: 'Consulter P&L', verb: 'INSPECT' }],
                  rawAudit: { margin: 0.942, currency: 'EUR' },
                },
              ],
            },
          ],
        },
        {
          id: 'bill',
          name: 'Bill · Market Signals',
          headerOrSidebar: 'header',
          icon: '📡',
          badge: 'Radar Signaux',
          description: 'Détection continue des opportunités de marché et veille technologique haute fréquence.',
          level: 2,
          sections: [
            {
              id: 'sec-bill-radar',
              title: 'Signaux Marché Qualifiés',
              category: 'table',
              icon: '🎯',
              description: 'Opportunités scorées par impact et vélocité.',
              level: 3,
              dataset: [
                {
                  id: 'sig-01',
                  name: 'Demande Architectures Graph-Native',
                  type: 'market_signal',
                  status: 'VALIDÉ',
                  icon: '📈',
                  description: 'Accélération des besoins d’ontologies d’entreprise et d’OSDK.',
                  level: 4,
                  fields: [
                    { key: 'source', label: 'Source', type: 'string', value: 'arXiv & Trends 2026' },
                    { key: 'impact', label: 'Impact Estimé', type: 'badge', value: 'Élevé', color: 'emerald' },
                  ],
                  actions: [{ id: 'act-qualify-sig', label: 'Convertir en Offre', verb: 'POST' }],
                  rawAudit: { signal_id: 'sig-01', confidence: 0.96 },
                },
              ],
            },
          ],
        },
        {
          id: 'clara',
          name: 'Clara · Product Forge',
          headerOrSidebar: 'header',
          icon: '⚡',
          badge: 'SOPs 72h',
          description: 'Usine à standardiser les protocoles et franchiser les briques logicielles en moins de 72h.',
          level: 2,
          sections: [
            {
              id: 'sec-clara-sops',
              title: 'Standard Operating Procedures (SOPs)',
              category: 'table',
              icon: '📋',
              description: 'Protocoles industriels certifiés réplicables sans intervention humaine.',
              level: 3,
              dataset: [
                {
                  id: 'sop-coach-72h',
                  name: 'Kit Franchise Coach OS en < 72h',
                  type: 'sop',
                  status: 'READY_DEPLOY',
                  icon: '📦',
                  description: 'Déploiement clé en main d’un environnement d’accompagnement autonome.',
                  level: 4,
                  fields: [
                    { key: 'standard', label: 'Standard', type: 'badge', value: '$100M Monopole', color: 'purple' },
                    { key: 'version', label: 'Version', type: 'string', value: 'v2.4' },
                  ],
                  actions: [{ id: 'act-clone-sop', label: 'Instancier Kit', verb: 'EXEC' }],
                  rawAudit: { sop_id: 'sop-01', deploy_sla_hours: 72 },
                },
              ],
            },
          ],
        },
        {
          id: 'nardole',
          name: 'Nardole · File de Travaux & Dispatch',
          headerOrSidebar: 'header',
          icon: '⏳',
          badge: 'Dispatch L2',
          description: 'Supervision de la file des travaux Business OS et répartition vers les subagents.',
          level: 2,
          sections: [
            {
              id: 'sec-nardole-queue',
              title: 'Travaux en File & Baux Opérationnels',
              category: 'table',
              icon: '📥',
              description: 'Articles réclamés dans la file SQLite uc.db.',
              level: 3,
              dataset: [
                {
                  id: 'work-nardole-sample',
                  name: 'Dispatch Tâches Hebdomadaires',
                  type: 'work_item',
                  status: 'IDLE',
                  icon: '📋',
                  description: 'Tâches de fond attribuées aux 10 compagnons.',
                  level: 4,
                  fields: [
                    { key: 'priority', label: 'Priorité', type: 'badge', value: 'P1_HAUTE', color: 'amber' },
                    { key: 'attempts', label: 'Tentatives', type: 'number', value: 0 },
                  ],
                  actions: [{ id: 'act-refresh-queue', label: 'Actualiser File', verb: 'GET', endpoint: '/api/tech-os/kernel-state' }],
                  rawAudit: { work_id: 104, retries_max: 3 },
                },
              ],
            },
          ],
        },
      ],
    },

    // 4. DOCTOR 11 LIFE
    {
      id: 'doctor-11-life',
      name: '11e Docteur · Life Core',
      domaine: 'l1-life',
      kind: 'singleton',
      icon: '🌱',
      description: 'Souveraineté Personnelle, Énergie & Habitacle de Conscience · 11e Docteur, Amy, Rory, River.',
      level: 1,
      views: [
        {
          id: 'docteur',
          name: '11e Docteur · Énergie & Habitacle',
          headerOrSidebar: 'header',
          icon: '✨',
          badge: 'Life Core',
          description: 'Gouvernance de la vitalité, alignement Ikigai et protection de l’énergie de l’opérateur Amadou Kone.',
          level: 2,
          sections: [
            {
              id: 'sec-energy-gauges',
              title: 'Jauges Vitales & Sommeil',
              category: 'kpi',
              icon: '🔋',
              description: 'Suivi de l’énergie psychique et cognitive.',
              level: 3,
              dataset: [
                {
                  id: 'gauge-energy',
                  name: 'Niveau d’Énergie Matinal',
                  type: 'life_gauge',
                  status: 'OPTIMAL',
                  icon: '⚡',
                  description: 'Évaluation quotidienne de la batterie mentale.',
                  level: 4,
                  fields: [
                    { key: 'level', label: 'Niveau', type: 'badge', value: 'High', color: 'emerald' },
                    { key: 'deep_work_hours', label: 'Fenêtre Deep Work', type: 'string', value: '4.5 h' },
                  ],
                  actions: [{ id: 'act-log-energy', label: 'Enregistrer Rituel', verb: 'POST' }],
                  rawAudit: { score: 92, sleep_quality: 'high' },
                },
              ],
            },
          ],
        },
        {
          id: 'amy',
          name: 'Amy · Interface & Rituels',
          headerOrSidebar: 'header',
          icon: '🎨',
          badge: 'Design & Rituels',
          description: 'Habitacle esthétique et orchestration des rituels quotidiens.',
          level: 2,
          sections: [
            {
              id: 'sec-amy-rituals',
              title: 'Rituels Quotidiens Fixes',
              category: 'table',
              icon: '🌅',
              description: 'Horlogerie de vie inviolable.',
              level: 3,
              dataset: [
                {
                  id: 'rit-morning',
                  name: 'Rituel d’Ouverture & Clarté',
                  type: 'ritual',
                  status: 'DONE',
                  icon: '☀️',
                  description: 'Prise de conscience, hydratation et planification des 3 priorités.',
                  level: 4,
                  fields: [
                    { key: 'duration', label: 'Durée', type: 'string', value: '25 min' },
                    { key: 'compliance', label: 'Assiduité', type: 'badge', value: '100 %', color: 'emerald' },
                  ],
                  actions: [{ id: 'act-validate-rit', label: 'Valider Rituel', verb: 'POST' }],
                  rawAudit: { ritual_id: 'morning_01', completed: true },
                },
              ],
            },
          ],
        },
        {
          id: 'rory',
          name: 'Rory · Intégrité & RLS',
          headerOrSidebar: 'header',
          icon: '🛡️',
          badge: 'Garde Sécurité',
          description: 'Garde inviolable des frontières privées, Row Level Security et isolation des mémoires.',
          level: 2,
          sections: [
            {
              id: 'sec-rory-rls',
              title: 'Contrôles d’Intégrité & RLS',
              category: 'table',
              icon: '🔒',
              description: 'Vérification continue des politiques de sécurité des tables.',
              level: 3,
              dataset: [
                {
                  id: 'chk-rls-memories',
                  name: 'Isolation RLS public.memories',
                  type: 'rls_policy',
                  status: 'ENFORCED',
                  icon: '🛡️',
                  description: 'Cloisonnement strict des données personnelles.',
                  level: 4,
                  fields: [
                    { key: 'policy', label: 'Politique', type: 'badge', value: 'Multi-Tenant Isolation', color: 'emerald' },
                    { key: 'result', label: 'Test', type: 'string', value: 'PASS (Enforced)' },
                  ],
                  actions: [{ id: 'act-test-rls', label: 'Auditer RLS', verb: 'INSPECT' }],
                  rawAudit: { table: 'public.memories', rls: 'enabled', violations: 0 },
                },
              ],
            },
          ],
        },
        {
          id: 'river',
          name: 'River · Workflows Canvas n8n',
          headerOrSidebar: 'header',
          icon: '🌊',
          badge: 'Canvas Interactif',
          description: 'Studio visuel d’automatisation n8n léger sans conteneur lourd.',
          level: 2,
          sections: [
            {
              id: 'sec-river-canvas',
              title: 'Workflows Actifs sur le Canvas',
              category: 'workflow',
              icon: '🕸️',
              description: 'Chaînes d’action déclencheurs -> filtres -> transformateurs -> sorties.',
              level: 3,
              dataset: [
                {
                  id: 'wf-dark-factory',
                  name: 'Dark Factory & Autoreplication',
                  type: 'n8n_workflow',
                  status: 'READY',
                  icon: '🏭',
                  description: 'Workflow de génération automatique de code et tests unitaires.',
                  level: 4,
                  fields: [
                    { key: 'nodes_count', label: 'Nœuds Visuels', type: 'number', value: 5 },
                    { key: 'engine', label: 'Moteur', type: 'badge', value: 'Python Native', color: 'blue' },
                  ],
                  actions: [{ id: 'act-run-wf', label: 'Exécuter Workflow', verb: 'EXEC' }],
                  rawAudit: { script: 'dark_factory.py', success_rate: '100%' },
                },
              ],
            },
          ],
        },
      ],
    },

    // 5. OBSERVERS
    {
      id: 'observers',
      name: 'Observateurs',
      domaine: 'l0-tech',
      kind: 'multi',
      icon: '◉',
      description: 'Les 11 observateurs souverains — installés, à cloner, hébergés.',
      level: 1,
      views: [
        {
          id: 'registry',
          name: 'Registre des Observateurs',
          headerOrSidebar: 'sidebar',
          icon: '📜',
          badge: '11 Observateurs',
          description: 'Liste contractuelle des sondes d’observabilité.',
          level: 2,
          sections: [
            {
              id: 'sec-obs-list',
              title: 'Sondes Déclarées',
              category: 'table',
              icon: '📡',
              description: 'Cartographie des observateurs de l’écosystème ASpace.',
              level: 3,
              dataset: [
                {
                  id: 'obs-01',
                  name: 'Agent OS Desktop (Port 5555)',
                  type: 'observer',
                  status: 'INSTALLÉ',
                  icon: '🖥️',
                  description: 'Tableau de bord web temps réel et gestionnaire de fenêtres.',
                  level: 4,
                  fields: [
                    { key: 'port', label: 'Port Écoute', type: 'badge', value: '5555', color: 'emerald' },
                    { key: 'runtime', label: 'Runtime', type: 'string', value: 'Vite / Node / React' },
                  ],
                  actions: [{ id: 'act-ping-obs', label: 'Tester Connexion', verb: 'GET' }],
                  rawAudit: { port: 5555, http_code: 200 },
                },
              ],
            },
          ],
        },
      ],
    },

    // 6. MEMORIES
    {
      id: 'memories',
      name: 'Mémoires',
      domaine: 'l0-tech',
      kind: 'multi',
      icon: '✎',
      description: 'Notes durables & persistance locale. Backup en un clic.',
      level: 1,
      views: [
        {
          id: 'editor',
          name: 'Éditeur & Sauvegardes',
          headerOrSidebar: 'sidebar',
          icon: '📝',
          badge: 'Durable Layer',
          description: 'Gestion des notes de bord, export JSON et synchronisation.',
          level: 2,
          sections: [
            {
              id: 'sec-mem-list',
              title: 'Mémoires Actives',
              category: 'table',
              icon: '📓',
              description: 'Notes stockées dans l’adaptateur de stockage persistant.',
              level: 3,
              dataset: [
                {
                  id: 'mem-01',
                  name: 'Charte Canon V3 & Loi de Rick',
                  type: 'memory_note',
                  status: 'CERTIFIED',
                  icon: '📜',
                  description: 'Règles fondamentales et architecture souveraine d’Agent OS.',
                  level: 4,
                  fields: [
                    { key: 'law', label: 'Loi L0', type: 'badge', value: 'Rick : Réplication Inviolable', color: 'purple' },
                    { key: 'format', label: 'Format', type: 'string', value: 'OKF 0.2' },
                  ],
                  actions: [{ id: 'act-export-mem', label: 'Exporter Sauvegarde', verb: 'EXEC' }],
                  rawAudit: { verified_by: 'human:amdkn', okf_version: '0.2' },
                },
              ],
            },
          ],
        },
      ],
    },

    // 7. SUBAGENTS COCKPIT
    {
      id: 'subagents-roster',
      name: 'Subagents Cockpit',
      domaine: 'l0-tech',
      kind: 'singleton',
      icon: '🤖',
      description: 'Centre d’orchestration et d’interconnexion des 14 Subagents Antigravity (Rick, 3 Docteurs, 10 Compagnons).',
      level: 1,
      views: [
        {
          id: 'roster',
          name: 'Roster des 14 Subagents',
          headerOrSidebar: 'sidebar',
          icon: '👥',
          badge: '14 Agents',
          description: 'Cartographie temps réel des subagents spécialisés et de leurs baux.',
          level: 2,
          sections: [
            {
              id: 'sec-roster-agents',
              title: 'Agents Spécialisés Actifs',
              category: 'table',
              icon: '🤖',
              description: 'Statut opérationnel, missions et dernières activations.',
              level: 3,
              dataset: [
                {
                  id: 'agent-rick',
                  name: 'Rick (Meta-Orchestrator L0)',
                  type: 'subagent',
                  status: 'UNKNOWN',
                  icon: '👑',
                  description: 'Gouvernance globale, exécution de la Loi L0 et surveillance anti-rejeu.',
                  level: 4,
                  fields: [
                    { key: 'role', label: 'Rôle', type: 'badge', value: 'Meta-Architect', color: 'purple' },
                    { key: 'core', label: 'Core', type: 'string', value: 'L0_Tech_OS' },
                    { key: 'sla', label: 'SLA Éveil', type: 'badge', value: '< 2 s', color: 'emerald' },
                  ],
                  actions: [
                    { id: 'act-invoke-rick', label: 'Invoquer Rick', verb: 'POST', endpoint: '/api/tech-os/invoke-agent' },
                  ],
                  rawAudit: { agent: 'rick', core: 'kernel', autonomous: true },
                },
                {
                  id: 'agent-doc-13',
                  name: '13e Docteur (Kernel Machine)',
                  type: 'subagent',
                  status: 'UNKNOWN',
                  icon: '⚙️',
                  description: 'Noyau transactionnel SQLite, baux de possession et détection d’erreurs.',
                  level: 4,
                  fields: [
                    { key: 'role', label: 'Rôle', type: 'badge', value: 'Machine Governor', color: 'blue' },
                    { key: 'companions', label: 'Compagnons', type: 'string', value: 'Yas, Ryan, Graham' },
                  ],
                  actions: [
                    { id: 'act-invoke-d13', label: 'Invoquer 13e Docteur', verb: 'POST', endpoint: '/api/tech-os/invoke-agent' },
                  ],
                  rawAudit: { agent: 'doctor_13', core: '10_Tech_OS', state: 'active' },
                },
              ],
            },
          ],
        },
      ],
    },
  ];

  return {
    version: '2.0.0',
    rootName: 'Agent OS V2 CMS',
    description: 'Architecture Content Management System multi-niveaux pour les applications, vues, widgets et données souveraines.',
    apps,
  };
}
